name: auto merge
description: Automatically PR merge composite action
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
runs:
  using: composite
  steps:
    - name: Auto merge
      shell: bash
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        gh pr review --approve "${PR_URL}"
        gh pr edit "${PR_URL}" --title "(auto merged) ${PR_TITLE}"
        gh pr merge --auto --merge "${PR_URL}"
